### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by asmeikal** [lucacmps/projects#1]
I HAVE ISSUE WITH JAVA BEANS COFFEE. I DO NOT HAVE COFFEE GRINDER TO GRIND JAVA BEANS AND MAKE AMERICAN COFFEE AND PROGRAM. PLEASE HELP.

**Comment by lucacmps** [comment]
GO AWAY PLS THIS REPOSITORY IS FOR TESTING PURPOSE ONLY. I AM AFRAID I CANNOT HELP YOU.
